version: "3"

services:
  postgres-db:
    build: ./postgres-db
    volumes:
      - C:/Users/designer/booking-app/database_migration_with_docker/postgres-db:/var/lib/postgresql/data
    ports:
      - 7557:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
      - POSTGRES_DB=test_db